max-slots: 108

blacklist:
  - xybyn
  - dscc

database:
  #connection-string: "jdbc:sqlite:{path}\\players.db"
  connection-string: "jdbc:postgresql://localhost/postgres?user=postgres&password=postgres"
messages:
  ec-no-money:
    - "Нет денег или предыдущий слот закрыт! Ваш баланс: %balance%, нужно еще %diff%"
  slot-buy-success:
    - "Вы успешно приобрели слот %buy-slot% на странице %buy-page% за %buy-price%"
  slot-description:
    - "<слот>"
  page-description:
    - "<страница>"
  get-command-description:
    - "получить предмет игрока"
  set-command-description:
    - "установить предмет для игрока"
  item-set:
    - "Вы установили предмет в слот %slot% на странице %page% для игрока %player%"
  ec-no-item:
    - "У игрока %player% в слоте %slot% на странице %page% нет предмета!"
  ec-item-got:
    - "Вам был выдан предмет игрока %player% в слоте %slot% на странице %page%"
  ec-slot-unlocked:
    - "Вы успешно разблокировали слот %slot% на странице %page% за %price%"
  ec-no-permission-use-other:
    - "У вас нет прав пользоваться чужим эндер-сундуком!"
  ec-blacklist:
    - "Вы не можете взаимодействовать с эндер-сундуком данного игрока!"
  ec-desc-level1:
    - "%bullet% Доступно для Адепта и выше"
  ec-desc-level2:
    - "%bullet% Доступно для Мастера и выше"
  ec-desc-level3:
    - "%bullet% Доступно для Титана и выше"
  ec-desc-level4:
    - "%bullet% Доступно для Легенды и выше"
slots:
  default-opened:
    1: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
    #1: [9, 10, 11, 12, 13, 14, 15, 16, 17]

  prices:
    1:
      36:
        price: 10000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 35
      37:
        price: 50000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 36
      38:
        price: 100000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 37
      39:
        price: 200000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 38
      40:
        price: 400000
        desc-id: "messages.ec-desc-level1"
        currency: MONEY
        require-page: 1
        require-slot: 39
      41:
        price: 600000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 40
      42:
        price: 800000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 41
      43:
        price: 1000000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 42
      44:
        price: 2000000
        currency: MONEY
        desc-id: "messages.ec-desc-level1"
        require-page: 1
        require-slot: 43

    2:
      9:
        price: 10
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        require-page: 1
        require-slot: 44

      10:
        price: 20
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        require-page: 2
        require-slot: 9

      11:
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        price: 30
        require-page: 2
        require-slot: 10

      12:
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        price: 40
        require-page: 2
        require-slot: 11

      13:
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        price: 50
        require-page: 2
        require-slot: 12

      14:
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        price: 50
        require-page: 2
        require-slot: 13
      15:
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        price: 50
        require-page: 2
        require-slot: 14
      16:
        price: 50
        desc-id: "messages.ec-desc-level2"
        currency: LEVEL
        require-page: 2
        require-slot: 15
      17:
        currency: LEVEL
        desc-id: "messages.ec-desc-level2"
        price: 50
        require-page: 2
        require-slot: 16
      18:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 17
      19:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 18
      20:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 19
      21:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 20
      22:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 21
      23:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 22
      24:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 23
      25:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level3"
        require-slot: 24
      26:
        price: 200
        desc-id: "messages.ec-desc-level3"
        require-page: 2
        require-slot: 25
      27:
        price: 200
        desc-id: "messages.ec-desc-level4"
        require-page: 2
        require-slot: 26
      28:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level4"
        require-slot: 27
      29:
        price: 200
        require-page: 2
        require-slot: 28
        desc-id: "messages.ec-desc-level4"
      30:
        price: 200
        desc-id: "messages.ec-desc-level4"
        require-page: 2
        require-slot: 29
      31:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level4"
        require-slot: 30
      32:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level4"
        require-slot: 31
      33:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level4"
        require-slot: 32
      34:
        price: 200
        desc-id: "messages.ec-desc-level4"
        require-page: 2
        require-slot: 33
      35:
        price: 200
        require-page: 2
        desc-id: "messages.ec-desc-level4"
        require-slot: 34
      36:
        price: 200
        require-page: 2
        require-slot: 35
      37:
        price: 200
        require-page: 2
        require-slot: 36
      38:
        price: 200
        require-page: 2
        require-slot: 37
      39:
        price: 200
        require-page: 2
        require-slot: 38
      40:
        price: 200
        require-page: 2
        require-slot: 39

      41:
        price: 200
        require-page: 2
        require-slot: 40
      42:
        price: 200
        require-page: 2
        require-slot: 41
      43:
        price: 200
        require-page: 2
        require-slot: 42
      44:
        price: 200
        require-page: 2
        require-slot: 43
    3:
      9:
        price: 300
        require-page: 2
        require-slot: 44

      10:
        price: 300
        require-page: 3
        require-slot: 9

      11:
        price: 300
        require-page: 3
        require-slot: 10

      12:
        price: 300
        require-page: 3
        require-slot: 11

      13:
        price: 300
        require-page: 3
        require-slot: 12

      14:
        price: 300
        require-page: 3
        require-slot: 13
      15:
        price: 300
        require-page: 3
        require-slot: 14
      16:
        price: 300
        require-page: 3
        require-slot: 15
      17:
        price: 300
        require-page: 3
        require-slot: 16
      18:
        price: 300
        require-page: 3
        require-slot: 17
      19:
        price: 300
        require-page: 3
        require-slot: 18
      20:
        price: 300
        require-page: 3
        require-slot: 19
      21:
        price: 300
        require-page: 3
        require-slot: 20
      22:
        price: 300
        require-page: 3
        require-slot: 21
      23:
        price: 300
        require-page: 3
        require-slot: 22
      24:
        price: 300
        require-page: 3
        require-slot: 23
      25:
        price: 300
        require-page: 3
        require-slot: 24
      26:
        price: 300
        require-page: 3
        require-slot: 25
      27:
        price: 300
        require-page: 3
        require-slot: 26
      28:
        price: 300
        require-page: 3
        require-slot: 27
      29:
        price: 300
        require-page: 3
        require-slot: 28
      30:
        price: 300
        require-page: 3
        require-slot: 29
      31:
        price: 300
        require-page: 3
        require-slot: 30
      32:
        price: 300
        require-page: 3
        require-slot: 31
      33:
        price: 300
        require-page: 3
        require-slot: 32
      34:
        price: 300
        require-page: 3
        require-slot: 33
      35:
        price: 300
        require-page: 3
        require-slot: 34
      36:
        price: 300
        require-page: 3
        require-slot: 35
      37:
        price: 300
        require-page: 3
        require-slot: 36
      38:
        price: 300
        require-page: 3
        require-slot: 37
      39:
        price: 300
        require-page: 3
        require-slot: 38
      40:
        price: 300
        require-page: 3
        require-slot: 39

      41:
        price: 300
        require-page: 3
        require-slot: 40
      42:
        price: 300
        require-page: 3
        require-slot: 41
      43:
        price: 300
        require-page: 3
        require-slot: 42
      44:
        price: 300
        require-page: 3
        require-slot: 43